# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/faruk/exp_7/exp_7.srcs/sources_1/ip/bram_green/bram_green.xci
# IP: The module: 'bram_green' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/faruk/exp_7/exp_7.gen/sources_1/ip/bram_green/bram_green_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_green'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/faruk/exp_7/exp_7.srcs/sources_1/ip/bram_green/bram_green.xci
# IP: The module: 'bram_green' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/faruk/exp_7/exp_7.gen/sources_1/ip/bram_green/bram_green_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_green'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
